"""Build-time auto-linking of plain-text chapter cross-references.

The house style (spec/conventions.md) says chapters refer to each other
by decimal number ("see chapter 8.1") and never hard-code file paths in
prose. This Markdown extension keeps the sources that way while giving the
published site real links: during rendering it recognizes the repository's
cross-reference formats and wraps the decimal numbers in links to the
matching chapter page.

Recognized formats (anything else is left alone):

- "chapter 8.1" / "chapters 1.5 (governance), 1.6, and 2.1" / "chapters
  4.1-4.6", including ranges and "to"/"through" connectors;
- fully parenthesised references such as "(10.1)", "(see 5.3)", or
  "(10.2, 10.3)", where the parentheses contain nothing but references;
- bold lead-ins whose text is exactly a chapter number and its real title,
  as in the part introductions: "**1.1 Software engineering values:**";
- table cells (the references appendix): comma-separated runs of two or
  more chapter numbers, ranges, and "N.M Title" entries whose first word
  matches the chapter's real title.

Version numbers and quantities (WCAG 2.2, OAuth 2.0, Apache 2.0, an OKR
graded 1.0, a risk weight of 1.5) never match: they either fail the chapter
lookup, appear in a vetoed context (a product name directly before the
number), or lack the structural context the rules require. Code, headings,
and existing links are never touched.

The chapter map in guide_xref/chapters.py is generated by tools/gen_nav.py
(`just nav`) and checked against the files on disk by tests/validate.py.
"""

from __future__ import annotations

import posixpath
import re
from typing import Any
from xml.etree.ElementTree import Element

from markdown import Extension, Markdown
from markdown.treeprocessors import Treeprocessor

from .chapters import CHAPTERS

# Elements whose subtrees must never gain links.
_SKIP = {"a", "code", "pre", "kbd", "script", "style",
         "h1", "h2", "h3", "h4", "h5", "h6"}

_REF = r"\d{1,2}\.\d{1,2}"
# A chapter number that is not part of a larger number or version string
# (a trailing sentence period is fine; ".<digit>" is a version continuation).
TOKEN = re.compile(rf"(?<![\d.$])({_REF})(?!\d|\.\d|%)")

# A run of references reaching back to the word "chapter(s)", allowing
# parenthesised descriptions ("1.5 (governance),") and connectors.
_DESC = r"(?:\s*\([^()]*\))?"
_CONN = r"(?:[,;]?\s+(?:and\s+|or\s+|to\s+|through\s+)?|[,;]\s*|\s*[–-]\s*)"
CHAIN = re.compile(rf"(?i)\bchapters?[,:]?\s+(?:{_REF}{_DESC}{_CONN}?)*$")

# Parentheses that contain nothing but references (and separators).
_SEP = r"(?:[,;]\s*|\s*[–-]\s*)"
PAREN_PRE = re.compile(rf"\((?:see\s+)?(?:{_REF}{_SEP})*$")
PAREN_POST = re.compile(rf"^(?:{_SEP}{_REF})*\)")

# Ranges such as "5.1-5.6" (used standalone only inside table cells).
RANGE_PRE = re.compile(rf"{_REF}\s*[–-]\s*$")
RANGE_POST = re.compile(rf"^\s*[–-]\s*{_REF}")

# Comma-separated runs of two or more references (table cells only).
RUN = re.compile(rf"{_REF}(?:\s*[,;]\s*{_REF})+")

# A product or version marker directly before a number vetoes the match.
VETO = re.compile(
    r"(?i)(?:\b(?:wcag|oauth|apache|swebok|rmf|http|tls|version|v)\s*\(?\s*"
    r"|guidelines\)\s*|\d\.\d\s*/\s*)$"
)

# Bold lead-ins: "N.M Title" with optional trailing punctuation.
STRONG = re.compile(rf"^({_REF})\s+(.+?)[.:]?$", re.S)


def _title_of(num: str) -> str:
    return CHAPTERS[num][1]


def _href(num: str, page_dir: str) -> str:
    return posixpath.relpath(f"chapters/{CHAPTERS[num][0]}", page_dir)


def _page_dir(md: Markdown, fallback: str) -> str | None:
    """Resolve the docs-relative directory of the page being rendered."""
    if fallback:
        return posixpath.dirname(fallback)
    try:
        from zensical.extensions.context import ContextPreprocessor
    except ImportError:
        return None
    ctx = ContextPreprocessor.from_markdown(md)
    if ctx is None or not getattr(ctx.page, "path", None):
        return None
    return posixpath.dirname(ctx.page.path)


class XrefTreeprocessor(Treeprocessor):
    """Wrap recognized plain-text chapter references in links."""

    def __init__(self, md: Markdown, page_path: str | None):
        super().__init__(md)
        self._page_path = page_path

    def run(self, root: Element) -> None:
        page_dir = _page_dir(self.md, self._page_path)
        if page_dir is None:
            return
        self._walk(root, page_dir, in_cell=False)

    # -- tree walking ------------------------------------------------------

    def _walk(self, el: Element, page_dir: str, in_cell: bool) -> None:
        if el.tag in _SKIP:
            return
        if el.tag == "strong" and self._link_strong(el, page_dir):
            return
        in_cell = in_cell or el.tag == "td"
        for child in list(el):
            self._walk(child, page_dir, in_cell)
        self._link_text_nodes(el, page_dir, in_cell)

    def _link_strong(self, el: Element, page_dir: str) -> bool:
        """Link a bold "N.M Title" lead-in when the title is the real one."""
        if len(el) or not el.text:
            return False
        m = STRONG.match(el.text.strip())
        if not m or m.group(1) not in CHAPTERS:
            return False
        title = _title_of(m.group(1))
        if m.group(2).strip().casefold() != title.casefold():
            return False
        link = self._make_link(m.group(1), page_dir)
        link.text, el.text = el.text, None
        el.append(link)
        return True

    def _link_text_nodes(self, el: Element, page_dir: str, in_cell: bool) -> None:
        """Split the text content of `el`, wrapping matched refs in links."""
        # el.text, then each child's tail, hold the raw text of this element
        original = list(el)
        parts = self._split(el.text, page_dir, in_cell)
        if parts is not None:
            el.text = parts[0]
            for offset, (link, tail) in enumerate(parts[1]):
                link.tail = tail
                el.insert(offset, link)
        for child in original:
            parts = self._split(child.tail, page_dir, in_cell)
            if parts is not None:
                child.tail = parts[0]
                anchor = child
                for link, tail in parts[1]:
                    link.tail = tail
                    el.insert(list(el).index(anchor) + 1, link)
                    anchor = link

    def _split(self, text, page_dir, in_cell):
        """Return (leading_text, [(link, tail), ...]) or None if no match."""
        if not text or not TOKEN.search(text):
            return None
        pieces: list[tuple[int, int, str]] = []
        for m in TOKEN.finditer(text):
            if m.group(1) in CHAPTERS and self._matches(text, m, in_cell):
                pieces.append((m.start(), m.end(), m.group(1)))
        if not pieces:
            return None
        lead = text[: pieces[0][0]]
        result = []
        for i, (s, e, num) in enumerate(pieces):
            link = self._make_link(num, page_dir)
            link.text = text[s:e]
            nxt = pieces[i + 1][0] if i + 1 < len(pieces) else len(text)
            result.append((link, text[e:nxt]))
        return (lead, result)

    # -- matching rules ----------------------------------------------------

    def _matches(self, text: str, m: re.Match, in_cell: bool) -> bool:
        # bound the look-behind window so anchored searches stay cheap
        pre, post = text[max(0, m.start() - 250): m.start()], text[m.end():]
        if VETO.search(pre):
            return False
        if CHAIN.search(pre):
            return True
        if PAREN_PRE.search(pre) and PAREN_POST.match(post):
            return True
        if in_cell:
            if RANGE_PRE.search(pre) or RANGE_POST.match(post):
                return True
            # part of a comma-separated run of two or more references
            for run in RUN.finditer(text):
                if run.start() <= m.start() and m.end() <= run.end():
                    return True
            # "N.M Title..." where the first word matches the real title
            title = _title_of(m.group(1))
            first = re.match(r"\s+([A-Za-z][\w/-]*)", post)
            if first and title.split()[0].casefold() == first.group(1).casefold():
                return True
        return False

    def _make_link(self, num: str, page_dir: str) -> Element:
        link = Element("a")
        link.set("href", _href(num, page_dir))
        link.set("title", f"{num} {_title_of(num)}")
        return link


class GuideXrefExtension(Extension):
    """Markdown extension wiring up the cross-reference treeprocessor."""

    def __init__(self, **kwargs: Any):
        # page_path is only used by the tests; in a Zensical build the page
        # path comes from the rendering context
        self.config = {"page_path": ["", "Docs-relative path of the page"]}
        super().__init__(**kwargs)

    def extendMarkdown(self, md: Markdown) -> None:
        md.registerExtension(self)
        processor = XrefTreeprocessor(md, self.getConfig("page_path"))
        # after inline processing (20), before Zensical's link rewriting (0)
        md.treeprocessors.register(processor, "guide_xref", 1)


def makeExtension(**kwargs: Any) -> GuideXrefExtension:
    return GuideXrefExtension(**kwargs)
