#!/usr/bin/env python3
import os, re, glob
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS=f"{ROOT}/docs"
CH=f"{DOCS}/chapters"
SITE_URL="https://software-engineering-guide.github.io/software-engineering-guide/"
def read(p): return open(p).read()
def write(p,t): open(p,"w").write(t)

PART_TITLES={1:"People",2:"Software Programming",3:"Systems",4:"Security",5:"UI/UX Design",
6:"Artificial Intelligence",7:"Data, Analytics, and Insight",8:"Automation",
9:"Operations, Reliability, and Observability",10:"Project/Product/Program Management",
11:"Flow: Discovery and Delivery Pipelines",12:"Appendices"}

def dec(fp):
    m=re.match(r'(\d+)\.(\d+)-', os.path.basename(fp)); return (int(m.group(1)),int(m.group(2)))
def h1title(fp):
    for ln in read(fp).splitlines():
        if ln.startswith("# "): return ln[2:].strip()
    return os.path.basename(fp)
def label_for(fp):
    t=h1title(fp)
    # strip redundant "Introduction to Part N: " for intro rows -> label "N.0 Introduction"
    m=re.match(r'(\d+\.0)\s+Introduction', t)
    return f"{m.group(1)} Introduction" if m else t

files=sorted(glob.glob(f"{CH}/*.md"), key=dec)
byp={}
for f in files: byp.setdefault(dec(f)[0],[]).append(f)
bynum={f"{dec(f)[0]}.{dec(f)[1]}": f for f in files}

# ---- guide_xref/chapters.py (chapter map for the auto-linking extension) ----
xref=["# Generated by tools/gen_nav.py (`just nav`). Do not edit by hand.",
 '"""Chapter map used by the guide_xref Markdown extension."""',"","CHAPTERS = {"]
for f in files:
    num=f"{dec(f)[0]}.{dec(f)[1]}"
    title=re.sub(r'^\d+\.\d+\s+','',h1title(f))
    xref.append(f'    "{num}": ({os.path.basename(f)!r}, {title!r}),')
xref+=["}",""]
write(f"{ROOT}/guide_xref/chapters.py","\n".join(xref))

# ---- TOC body (shared by README + site home + TOC page) ----
def toc_body(pathprefix):
    out=[]
    for p in sorted(byp):
        out.append(f"### Part {p}: {PART_TITLES[p]}")
        for f in sorted(byp[p], key=dec):
            rel=f"{pathprefix}{os.path.basename(f)}"
            out.append(f"- [{label_for(f)}]({rel})")
        out.append("")
    return "\n".join(out)

INTRO="""This is a guidebook of good practices for **software developer
teams**, including for startups, enterprises, and government organizations.

The guide spans ways of working, programming craft, architecture, security,
AI, data and analytics, UI/UX, automation, delivery, operations, flow,
management, and the full breadth of the software engineering body of
knowledge."""

HOW_TO_READ="""## How to read this guidebook

Parts are whole numbers; chapters are decimals. Chapter **N.0** introduces each
part; **N.1, N.2, …** are its chapters. Part 12 collects the appendices
(glossary, checklists, templates, maturity self-assessment, references,
adoption roadmap, and index). Each chapter states principles, recommendations,
trade-offs, examples (enterprise and government), a business case (ROI/TCO),
anti-patterns, a maturity model, discussion questions, and references. Adopt
incrementally; do not big-bang."""

THEMES="""## Cross-cutting themes

Security, privacy, and accessibility appear in every part, not once. Automation
and "everything as code" underpin repeatability and audit. Measurement and
feedback loops turn practices into learning systems. Documentation and
knowledge continuity protect against turnover and scale. Regulatory and
government constraints are treated as design inputs, not afterthoughts."""

# ---- README (repository home page) ----
readme=f"""# Software Engineering Guide

{INTRO}

The guide is published as a website at
<{SITE_URL}>.

## Table of contents

{toc_body("docs/chapters/")}
{THEMES}

## The documentation site

The book is built into a static website with [Zensical](https://zensical.org/)
and deployed to GitHub Pages on every push to `main`. See [SITE.md](SITE.md)
for how the site is built, served locally, and deployed.
"""
write(f"{ROOT}/README.md", readme)

# ---- docs/index.md (site home page) ----
home=f"""# Software Engineering Guide

{INTRO}

- **[What is software engineering?](front-matter/what-is-software-engineering.md):** start here
- **[Introduction](front-matter/introduction.md):** what this book is and how to read it
- **[Table of contents](front-matter/table-of-contents.md):** the full chapter list
- **[Specification](spec/index.md):** outline, principles, backlog, and checklists

{HOW_TO_READ}

## Table of contents

{toc_body("chapters/")}
{THEMES}

## Beyond the chapters

- **[Examples](examples/index.md):** small, concrete examples of the book's ideas in use.
- **[About this project](project/index.md):** how the book is built, checked, and published.
- **[Contributing](contributing/index.md):** how to help, and the house style rules.
"""
write(f"{DOCS}/index.md", home)

# ---- docs/front-matter/table-of-contents.md ----
toc=f"""# Table of contents

Parts are whole numbers; chapters are decimals (chapter **N.0** introduces each
part). See also the [Introduction](introduction.md).

{toc_body("../chapters/")}"""
write(f"{DOCS}/front-matter/table-of-contents.md", toc)

# ---- zensical.toml nav block ----
def toml_str(s): return '"'+s.replace("\\","\\\\").replace('"','\\"')+'"'
def nav_block():
    out=["nav = ["]
    def leaf(label, path, ind=1):
        out.append("  "*ind+f"{{ {toml_str(label)} = {toml_str(path)} }},")
    def section(label, items, ind=1):
        out.append("  "*ind+f"{{ {toml_str(label)} = [")
        for lb, pth in items: leaf(lb, pth, ind+1)
        out.append("  "*ind+"] },")
    leaf("Home", "index.md")
    section("Front matter", [
        ("What is software engineering?", "front-matter/what-is-software-engineering.md"),
        ("Introduction", "front-matter/introduction.md"),
        ("Table of contents", "front-matter/table-of-contents.md"),
    ])
    for p in sorted(byp):
        section(f"Part {p}: {PART_TITLES[p]}",
                [(label_for(f), f"chapters/{os.path.basename(f)}") for f in sorted(byp[p], key=dec)])
    section("Specification", [
        ("Overview", "spec/index.md"),
        ("Structure", "spec/structure.md"),
        ("Conventions", "spec/conventions.md"),
        ("Roadmap", "spec/roadmap.md"),
    ])
    section("Examples", [
        ("Overview", "examples/index.md"),
        ("ADR example", "examples/adr-example.md"),
        ("OKRs example", "examples/okrs-example.md"),
    ])
    section("Contributing", [
        ("How to contribute", "contributing/index.md"),
        ("Authoring chapters", "contributing/authoring.md"),
        ("Generated navigation", "contributing/navigation.md"),
        ("The validation suite", "contributing/testing.md"),
        ("Style rules", "contributing/style-rules.md"),
        ("Chapter template", "contributing/chapter-template.md"),
        ("Part index", "contributing/part-index.md"),
    ])
    section("Project", [
        ("About this project", "project/index.md"),
        ("Changelog", "project/changelog.md"),
    ])
    out.append("]")
    return "\n".join(out)

zt_path=f"{ROOT}/zensical.toml"
zt=read(zt_path)
BEGIN="# --- BEGIN GENERATED NAV (regenerate with `just nav`; do not edit by hand) ---"
END="# --- END GENERATED NAV ---"
assert BEGIN in zt and END in zt, "zensical.toml is missing the generated-nav markers"
zt=zt[:zt.index(BEGIN)+len(BEGIN)]+"\n"+nav_block()+"\n"+zt[zt.index(END):]
write(zt_path, zt)

# ---- docs/chapters/12.7-index.md (subject index) ----
idxchap=[f for f in files if dec(f)[1]>=1 and dec(f)[0]<=11]  # substantive chapters, parts 1-11
terms=["accessibility","agile","API","architecture decision record","A/B testing","blameless","blue-green",
 "bounded context","canary","capacity planning","chaos engineering","CI/CD","circuit breaker","code review",
 "compliance","configuration management","containers","continuous delivery","Conway's Law","CQRS","data governance",
 "data mesh","dependency","design system","DevSecOps","Diátaxis","Domain-Driven Design","DORA","encryption",
 "error budget","estimation","event sourcing","experimentation","feature flag","FedRAMP","FinOps","fitness function",
 "formal methods","GDPR","GitOps","hallucination","incident","InnerSource","Kanban","Kubernetes","Little's Law",
 "maintenance","maturity model","microservices","MLOps","monorepo","north star","observability","OKR",
 "OpenTelemetry","OWASP","pair programming","plain language","policy as code","postmortem","privacy",
 "progressive delivery","prompt engineering","quality attributes","queueing theory","RAG","refactoring",
 "reliability","requirements","retrospective","reuse","RFC","risk register","RTO","SBOM","Scrum",
 "secrets management","service level objective","shift-left","SLSA","SMART","SOLID","STRIDE","supply chain",
 "technical debt","test automation","threat modeling","toil","total cost of ownership","traceability",
 "trunk-based development","UML","utilization","value stream","vector database","velocity","WCAG","zero-trust"]
entries={}
for term in terms:
    pat=re.compile(r'(?i)(?<![A-Za-z])'+re.escape(term)+r'(?![A-Za-z])')
    hits=[f"{dec(f)[0]}.{dec(f)[1]}" for f in idxchap if pat.search(read(f))]
    if hits: entries[term]=hits
out=["# 12.7 Index","","A subject index of key concepts and the chapters that cover them.",
 "Terms are defined in the Glossary (chapter 12.1).",""]
byl={}
for term in sorted(entries,key=lambda s:s.lower()):
    L=term[0].upper() if term[0].isalpha() else "#"; byl.setdefault(L,[]).append(term)
def chlink(num): return f"[{num}]({os.path.basename(bynum[num])})"
for L in sorted(byl):
    out+=[f"## {L}",""]+[f"- **{t}**: {', '.join(chlink(n) for n in entries[t])}" for t in byl[L]]+[""]
write(f"{CH}/12.7-index.md","\n".join(out))

# spec/index.md and spec/structure.md are hand-authored source-of-truth (not generated here).

print("nav generated. parts:", {p:len(byp[p]) for p in sorted(byp)})
print("index terms:", len(entries))
